import AlertsBlock        from '@common/Alerts.vue';
import SummaryBlock       from '@components/shared/summary/SummaryBlock.vue';
import AuthBlock          from '@components/public/auth/AuthBlock.vue';
import FilesBlock         from '@components/public/files/FilesBlock.vue';
import FoldersBlock       from '@components/public/folders/FoldersBlock.vue';
import FileItem           from '@components/public/news/FileItem.vue';
import NewsBlock          from '@components/public/news/NewsBlock.vue';
import NewsItemEdit       from '@components/public/news/list/NewsItemEdit.vue';
import NewsShow           from '@components/public/news/NewsShow.vue';
import AnnouncementsBlock from '@components/public/news/announcements/AnnouncementsBlock.vue';
import IndexPage          from '@components/public/pages/IndexPage.vue';
import PageEditor         from '@components/public/pages/PageEditor.vue';
import CounterForm        from '@components/public/requests/CounterForm.vue';
import PaymentForm        from '@components/public/requests/PaymentForm.vue';
import HelpDeskForm       from '@components/public/requests/HelpDeskForm.vue';
import SearchBlock        from '@components/public/search/SearchBlock.vue';
import RestorePage        from '@components/public/auth/RestorePage.vue';
import ShareButton        from '@components/public/ShareButton.vue';
import ResetPassword      from '@components/public/auth/ResetPassword.vue';
import SetPassword        from '@components/public/auth/SetPassword.vue';

export function registerAppComponents (app) {
    app.component('alerts-block', AlertsBlock);
    app.component('summary-block', SummaryBlock);
    app.component('auth-block', AuthBlock);
    app.component('files-block', FilesBlock);
    app.component('folders-block', FoldersBlock);
    app.component('file-item', FileItem);
    app.component('news-block', NewsBlock);
    app.component('news-item-edit', NewsItemEdit);
    app.component('news-show', NewsShow);
    app.component('announcements-block', AnnouncementsBlock);
    app.component('index-page', IndexPage);
    app.component('page-editor', PageEditor);
    app.component('counter-form', CounterForm);
    app.component('payment-form', PaymentForm);
    app.component('help-desk-form', HelpDeskForm);
    app.component('search-block', SearchBlock);
    app.component('restore-page', RestorePage);
    app.component('reset-password', ResetPassword);
    app.component('set-password', SetPassword);
    app.component('share-button', ShareButton);
}
